### PR TITLE
Exercise 1.13 - fixed index out of bounds

### LINKED ISSUE #22: Exercise 1_13
1. Index out of bounds:
```
// Initialize the histogram array with 0
  int i;
  for (i = 0; i <= BUFFER; ++i) 
  {
    histogram[i] = 0;
  }
```
2. Index out of bounds: -1, when input starts with spaces. Need add check like this:
```
        if (word_count_index > 0 && word_count_index <= BUFFER) // <-- add check
        {
          ++histogram[word_count_index - 1];

          if (histogram[word_count_index - 1] > max_word_count)
          {
            max_word_count = histogram[word_count_index - 1];
          }

          if (histogram_length < word_count_index - 1)
          {
            histogram_length = word_count_index - 1;
          }

          word_count_index = 0;
        }
```

### PR DESCRIPTION
**Pull request by DenSel86**
1. Fixed index out of bounds at initializing the array.

2. Fixed index out of bounds when input starts with spaces:
The array cell with index -1 is accessed during the first iteration of the for-loop if the input starts with spaces.
You can correct the initial value from **FALSE** to **TRUE** of the variable _new_word_ to solve the problem. But you can also refuse it because it is interconnected with the variable _word_count_index_ and use _word_count_index_ for the check.

This PR closes #22 issue.

### CODE REVIEW

File: chapter_1/exercise_1_13/histogram.c [hunk 1]
```diff
@@ -28,9 +27,8 @@ int main(void)
   {
     if (c == ' ' || c == '\t' || c == '\n')
     {
-      if (!new_word)
+      if (word_count_index > 0)
```
Comment (ohkimur) [inline chapter_1/exercise_1_13/histogram.c:30]: @DenSel86 This is a very nice optimization. Great job! 💪

**Review by ohkimur — APPROVED** [review]
@DenSel86 Congratulations! You did a very good job. 🥳

**Comment by ohkimur** [comment]
This PR closes #22 issue.

File: chapter_1/exercise_1_13/histogram.c (hunk 1 above)
Comment (DenSel86) [reply chapter_1/exercise_1_13/histogram.c:30]: Thanks :)
