### PR TITLE
fix exercise 1-12 edge cases

### LINKED ISSUE #58: wrong result for 'escape sequence chain' - Exercise 1-12.
https://github.com/ohkimur/the-c-programming-language-2nd-edition-solutions/blob/1506a2a6fb59d663aa36c382873a9c3d0f486089/chapter_1/exercise_1_12/copy_io_nl.c#L1-L22

Imagine the input being ` \t`

1. `c = ' '`
2. `last_char = ' '` and `c = '\t'` here `c != last_char` evaluates to true and a newline would be printed to stdout although no new word started

e.g.
```
This \tTest
```

I think having additional checks would fix this. I just recently started learning C so I am potentially missing something here..

```c
#include <stdio.h>

int main() {
  int c, prev;
  prev = EOF;

  while ((c = getchar()) != EOF) {
    if (c == ' ' || c == '\t' || c == '\n') {
      if (prev != ' ' && prev != '\t' && prev != '\n') {
        putchar('\n');
      }
    } else {
      putchar(c);
    }

    prev = c;
  }

  return 0;
}
```

### PR DESCRIPTION
**Pull request by caldotdev**
closes #58 

I just added the solution suggested in the issue. Please double check 🤔

Hopefully the formatting is fine 👍🏻

### CODE REVIEW

File: chapter_1/exercise_1_12/copy_io_nl.c [hunk 1]
```diff
@@ -2,22 +2,21 @@
 
 int main()
 {
-  char c;
-  char last_char = -1;
+  int c, prev;
+  prev = EOF;
```
Comment (ohkimur) [inline chapter_1/exercise_1_12/copy_io_nl.c:6]: @caldotdev You can do initialization during declaration, so you don't need this additional line here. Also, I would appreciate improving the naming of the `prev` variable to `previous_char`. It might seem like a long name, but I would advocate that it improves readability, especially for people who try to understand the solution more easily.

**Review by ohkimur — CHANGES_REQUESTED** [review]
@caldotdev Thanks very much for your contribution. I really appreciate it. There are a few minor things that I requested that you change before merging.

File: chapter_1/exercise_1_12/copy_io_nl.c (hunk 1 above)
Comment (caldotdev) [reply chapter_1/exercise_1_12/copy_io_nl.c:6]: wouldn't be

```c
int char
int last_char
```

be more intuitive and consistent here?

File: chapter_1/exercise_1_12/copy_io_nl.c [hunk 2]
```diff
@@ -2,22 +2,21 @@
 
 int main()
 {
-  char c;
-  char last_char = -1;
+  int c, prev;
```
[the remark this answers is not in the document]
Comment (caldotdev) [reply chapter_1/exercise_1_12/copy_io_nl.c]: done

**Review by ohkimur — APPROVED** [review]
@caldotdev Great job!
